config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }
  devise_for :end_users, controllers: {
    sessions: 'end_users/sessions',
    passwords: 'end_users/passwords',
    registrations: 'end_users/registrations'
  }

	root 'home#top'
	get '/about', to: 'home#about'
	get '/admin', to: 'admin#top'
	patch '/end_users/withdraw', to: 'public/end_users#withdraw', as: 'withdraw'
	get '/orders/thanks', to: 'public/orders#thanks'
	get '/end_users/confirm', to: 'public/end_users#confirm'
	post '/orders/confirm', to: 'public/orders#confirm'
  delete '/cart_items/destroy_all', to: 'public/cart_items#destroy_all'
  get '/admin/searches', to: 'admin/searches#search'
  
  scope module: 'public' do
    resource :end_user, only: [:show, :edit, :update]
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :create, :edit, :new]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :items, only: [:index, :show]
  end

  namespace :admin do
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :end_users, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  validates :quantity, numericality: {only_integer: true}

  belongs_to :end_user
  belongs_to :item

  def sub_total
    BigDecimal(self.item.price) * BigDecimal("1.1") * BigDecimal(self.quantity)
  end
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders


  validates :family_name, :first_name, :postal_code, :address, :phone_number, presence: true
  # 全角カナ入力のバリデーション
  validates :family_name_kana, :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}

  has_many :cart_items
  has_many :shipping_addresses

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true, uniqueness: true,
                    length: {maximum: 20}
  validates :is_active, inclusion: {in: [true, false]}
  has_one :item
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: {maximum: 30}
  validates :introduction, presence: true, length: {maximum: 100}
  validates :price, presence: true, numericality: {only_integer: true}
  validates :sales_status, inclusion: {in: [true, false]}

  belongs_to :genre
  has_many :cart_items
  attachment :image
  has_many :order_items
  has_many :orders, through: :order_items

  def price_with_tax
    (BigDecimal(self.price) * BigDecimal("1.1")).ceil.to_s(:delimited)
  end

  def is_on_sale?
    if self.sales_status == true
      "販売中"
    elsif self.sales_status == false
      "売切れ"
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :end_user
  has_many :order_items
  has_many :items, through: :order_items

  enum status: {
    入金待ち:0,入金確認:1,製作中:2,発送準備中:3,発送済み:4
  }

  def total_count
  	@total_order_quantity = 0
  	@order_items = self.order_items
  	@order_items.each do |order_item|
  	  @total_order_quantity += order_item.quantity
    end
  	return @total_order_quantity
  end

  POSTAGE = 800
  # 送料定義

  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  
  after_update :change_status
  protected
  def change_status
    if self.status == "入金確認"
      self.order_items.update_all(making_status: 1)
    end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }

  after_update :change_status
  protected
	def change_status
	  if self.making_status == "製作中"
		  self.order.update(status: 2)
	  elsif self.order.order_items.all?{|order_item|order_item.making_status == "製作完了"}
		self.order.update(status: 3)
	  end
	end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true
  validates :name, presence: true

  belongs_to :end_user

  def postal_code_address_name
    self.postal_code + "　" + self.address + "　" + self.name
  end
end

app/controllers/admin/base.rb
class Admin::Base < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::Base

  def index
    case params[:order_sort]
    when "1"
      @end_user = EndUser.find(params[:end_user_id])
      @orders = @end_user.orders.all.order(created_at: :desc).page(params[:page]).per(10)
    when "2"
      @orders = Order.where("created_at >= ?", Time.zone.now.beginning_of_day).all.order(created_at: :desc).page(params[:page]).per(10)
     else
      @orders = Order.all.order(created_at: :desc).page(params[:page]).per(10)
    end
  end

  def show
    @order = Order.find(params[:id])
  end
  def update
  	@order = Order.find(params[:id])
  	@order.update(order_params)
      redirect_back(fallback_location: root_path)
  end

  private
  def order_params
  	params.require(:order).permit(:status)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
	def top
		@order = Order.where(created_at: Time.zone.now.all_day)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
		case resource
		when EndUser
			root_path
		when Admin
			admin_path
		end
	end

	def after_sign_out_path_for(resource)
		if resource == :admin
		new_admin_session_path
		else
		root_path
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  	@genres = Genre.where(is_active: true)
    #注文のあった商品を売上金額順に表示
    @items = Item.find(OrderItem.group(:item_id).order("sum(ordering_price) desc").limit(4).pluck(:item_id))
    #テスト対策 まだどの商品も売れてない場合はID順で4つ表示
    if @items.count == 0
      @items = Item.limit(4)
    end
  end

  def about
  end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/orders/index.html.erb
<!-- admin/orders/index -->
<div class="container">
  <div class="col-xs-10 col-xs-offset-1">
		<h3 class="item-headline">注文履歴一覧</h3>
		<table class="order-table table">
	    <thead class="thead-dark">
	      <tr class="active">
	        <th>購入日時</th>
	        <th>購入者</th>
	        <th>注文個数</th>
	        <th>注文ステータス</th>
	      </tr>
	    </thead>
			<tbody>
				<% @orders.each do |order| %>
					<tr>
						<td>
							<%= link_to(admin_order_path(order), id: "order_#{order.id}" ) do %>
								<%= order.created_at.strftime("%Y-%m-%d %H:%M") %>
							<% end %>
						</td>
				 		<td><%= order.end_user.family_name %><%= order.end_user.first_name %></td>
			  		<td><%= order.total_count %></td>
			  		<td><%= order.status %></td>
				  </tr>
				<% end %>
		  </tbody>
		</table>
		<%= paginate @orders %>
	</div>
</div>

app/views/admin/orders/show.html.erb
<!-- admin/orders/show -->
<div class="container">
	<h3 class="item-headline">注文履歴詳細</h3><br>
	<div class="order-info col-xs-9">
		<strong class="col-xs-3">購入者</strong>
		<%= link_to admin_end_user_path(@order.end_user) do %>
		<%= @order.end_user.family_name %><%= @order.end_user.first_name %>
		<% end %>
	</div>
<!-- 購入者情報 -->
	<div class="order-info col-xs-9">
		<strong class="col-xs-3">配送先</strong>
			〒<%= @order.postal_code %>　<%= @order.address %>　　　
			<%= @order.name %>
	</div>
	<div class="order-info col-xs-9">
		<strong class="col-xs-3">支払方法</strong>
		<%= @order.payment_method %>
	</div>
	<div class="order-info col-xs-9">
		<strong class="col-xs-3">注文ステータス</strong>
		<div class="col-xs-3">
			<%= form_for [:admin, @order] do |f| %>
				<%= f.select :status, Order.statuses.keys, class:"form-control" %>
  		    <%= f.submit '更新', class:"btn btn-primary btn-xs" %>
  	        <% end %>
		</div>
	</div>

	<!-- 商品内訳 -->
	<div class="order-table col-lg-7">
		<table class="table">
		  <thead class="thead-dark">
		    <tr class="active">
		      <th>商品名</th>
		      <th>単価(税込)</th>
		      <th>数量</th>
		      <th>小計</th>
		      <th>製作ステータス</th>
		    </tr>
		  </thead>
			<tbody>
				<% @order.order_items.each do |order_item| %>
					<tr>
						<td>
							<%= order_item.item.name %>
						</td>
				 		<td><%= order_item.item.price_with_tax %></td>
			  		<td><%= order_item.quantity %></td>
			  		<td><%= order_item.ordering_price %></td>
			  		<td>
							<%= form_for [:admin, order_item] do |f| %>
								<%= f.select :making_status, OrderItem.making_statuses.keys, class:"form-control" %>
			      			<%= f.submit '更新', class:"btn btn-primary btn-xs" %>
							<% end %>
						</div>
			  		</td>
				  </tr>
				<% end %>
		  </tbody>
		</table>
	</div>
		<!-- 合計金額 -->
	<div class="price-table col-xs-4 col-xs-offset-1">
		<div class="takasa"><strong class="col-xs-5">商品合計</strong><%= @order.subtotal_price %>円</div>
		<div class="takasa"><strong class="col-xs-5">送料</strong><%= @order.postage %>円</div>
		<div class="takasa"><strong class="col-xs-5">請求金額合計</strong><strong class="text-left"><%= @order.subtotal_price+@order.postage %>円</strong></div>
	</div>
</div>