config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }
  devise_for :end_users, controllers: {
    sessions: 'end_users/sessions',
    passwords: 'end_users/passwords',
    registrations: 'end_users/registrations'
  }

	root 'home#top'
	get '/about', to: 'home#about'
	get '/admin', to: 'admin#top'
	patch '/end_users/withdraw', to: 'public/end_users#withdraw', as: 'withdraw'
	get '/orders/thanks', to: 'public/orders#thanks'
	get '/end_users/confirm', to: 'public/end_users#confirm'
	post '/orders/confirm', to: 'public/orders#confirm'
  delete '/cart_items/destroy_all', to: 'public/cart_items#destroy_all'
  get '/admin/searches', to: 'admin/searches#search'
  
  scope module: 'public' do
    resource :end_user, only: [:show, :edit, :update]
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :create, :edit, :new]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :items, only: [:index, :show]
  end

  namespace :admin do
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :end_users, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  validates :quantity, numericality: {only_integer: true}

  belongs_to :end_user
  belongs_to :item

  def sub_total
    BigDecimal(self.item.price) * BigDecimal("1.1") * BigDecimal(self.quantity)
  end
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders


  validates :family_name, :first_name, :postal_code, :address, :phone_number, presence: true
  # 全角カナ入力のバリデーション
  validates :family_name_kana, :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}

  has_many :cart_items
  has_many :shipping_addresses

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true, uniqueness: true,
                    length: {maximum: 20}
  validates :is_active, inclusion: {in: [true, false]}
  has_one :item
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: {maximum: 30}
  validates :introduction, presence: true, length: {maximum: 100}
  validates :price, presence: true, numericality: {only_integer: true}
  validates :sales_status, inclusion: {in: [true, false]}

  belongs_to :genre
  has_many :cart_items
  attachment :image
  has_many :order_items
  has_many :orders, through: :order_items

  def price_with_tax
    (BigDecimal(self.price) * BigDecimal("1.1")).ceil.to_s(:delimited)
  end

  def is_on_sale?
    if self.sales_status == true
      "販売中"
    elsif self.sales_status == false
      "売切れ"
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :end_user
  has_many :order_items
  has_many :items, through: :order_items

  enum status: {
    入金待ち:0,入金確認:1,製作中:2,発送準備中:3,発送済み:4
  }

  def total_count
  	@total_order_quantity = 0
  	@order_items = self.order_items
  	@order_items.each do |order_item|
  	  @total_order_quantity += order_item.quantity
    end
  	return @total_order_quantity
  end

  POSTAGE = 800
  # 送料定義

  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  
  after_update :change_status
  protected
  def change_status
    if self.status == "入金確認"
      self.order_items.update_all(making_status: 1)
    end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }

  after_update :change_status
  protected
	def change_status
	  if self.making_status == "製作中"
		  self.order.update(status: 2)
	  elsif self.order.order_items.all?{|order_item|order_item.making_status == "製作完了"}
		self.order.update(status: 3)
	  end
	end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true
  validates :name, presence: true

  belongs_to :end_user

  def postal_code_address_name
    self.postal_code + "　" + self.address + "　" + self.name
  end
end

app/controllers/admin/base.rb
class Admin::Base < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
	def top
		@order = Order.where(created_at: Time.zone.now.all_day)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
		case resource
		when EndUser
			root_path
		when Admin
			admin_path
		end
	end

	def after_sign_out_path_for(resource)
		if resource == :admin
		new_admin_session_path
		else
		root_path
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  	@genres = Genre.where(is_active: true)
    #注文のあった商品を売上金額順に表示
    @items = Item.find(OrderItem.group(:item_id).order("sum(ordering_price) desc").limit(4).pluck(:item_id))
    #テスト対策 まだどの商品も売れてない場合はID順で4つ表示
    if @items.count == 0
      @items = Item.limit(4)
    end
  end

  def about
  end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="container">
	<h1 class="about-headline">About</h1>
	<div class="about-text">
		<p>ながのCakeは全国発送可能なケーキ屋さんです。<br>
		   お子様からお年寄りの方までお召し上がりいただけるよう、<br>
		   様々なバリエーションをご用意しております。<br>
		   また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。<br>
		   ぜひご注文ください。<br>
		</p>
	</div>
	<div class="about-image">
		<%= image_tag "logo.png", width: "500px" %>
	</div>
</div>

app/views/home/top.html.erb
<div class="container">
	<div class="row">
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class:key) %>
		<% end %>
		<!-- ジャンル検索サイドバー表示 -->
		 <%= render 'public/items/genre_search', genres: @genres %>
		<div class="col-xs-9">
		<!-- 画像背景 -->
			<div class="top-visual">
				<div class="top-text-visual">
					<p class="top-text">
					ようこそ、<strong>ながのCAKE</strong> へ！<br>
					このサイトは、ケーキ販売のECサイトになります。<br>
					会員でない方も商品の閲覧はできますが、<br>
					購入には会員登録が必要になります。<br>
					</p>
				</div>
			</div>

			<!-- オススメ商品の表示 -->
      <% rank = 1 %>
			<div class="recommendation">
			<h2 class="recommendation-head"><strong>オススメ商品</strong></h2>
			<% @items.each do |item| %>
      			<div class="item-wrapper">
              <p><strong><%= rank %>位</strong></p>
        			<%= link_to item_path(item) do %>
          				<div class="item-image">
            			<%= attachment_image_tag item, :image, :fill, 150, 100, fallback: "no_image.jpg", size: '150x100' %>
         				</div>
          				<div class="item-description">
            				<p><%= item.name %></p>
            				<p>￥ <%= item.price_with_tax %></p>
          				</div>
        			<% end %>
      			</div>
            <% rank += 1 %>
    		<% end %>
    		<div class="col-xs-9 col-xs-offset-9">
    			<%= link_to 'もっと見る>', items_path %>
    		</div>
    		</div>
    	</div>
    </div>
</div>